[2022-12-12T05:37:38.854+0000] {processor.py:153} INFO - Started process (PID=91) to work on /opt/airflow/dags/etl.py
[2022-12-12T05:37:38.861+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2022-12-12T05:37:38.886+0000] {logging_mixin.py:137} INFO - [2022-12-12T05:37:38.886+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2022-12-12T05:37:39.081+0000] {logging_mixin.py:137} INFO - [2022-12-12T05:37:39.046+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 6, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2022-12-12T05:37:39.085+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2022-12-12T05:37:39.478+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etl.py took 0.647 seconds
[2022-12-12T05:39:02.842+0000] {processor.py:153} INFO - Started process (PID=174) to work on /opt/airflow/dags/etl.py
[2022-12-12T05:39:02.864+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2022-12-12T05:39:02.870+0000] {logging_mixin.py:137} INFO - [2022-12-12T05:39:02.870+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2022-12-12T05:39:03.175+0000] {logging_mixin.py:137} INFO - [2022-12-12T05:39:03.055+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 6, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2022-12-12T05:39:03.180+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2022-12-12T05:39:03.505+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etl.py took 0.679 seconds
[2022-12-12T05:39:34.240+0000] {processor.py:153} INFO - Started process (PID=240) to work on /opt/airflow/dags/etl.py
[2022-12-12T05:39:34.246+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2022-12-12T05:39:34.252+0000] {logging_mixin.py:137} INFO - [2022-12-12T05:39:34.252+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2022-12-12T05:39:34.290+0000] {logging_mixin.py:137} INFO - [2022-12-12T05:39:34.283+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 6, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2022-12-12T05:39:34.294+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2022-12-12T05:39:34.351+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etl.py took 0.122 seconds
[2022-12-12T05:40:07.570+0000] {processor.py:153} INFO - Started process (PID=297) to work on /opt/airflow/dags/etl.py
[2022-12-12T05:40:07.581+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2022-12-12T05:40:07.592+0000] {logging_mixin.py:137} INFO - [2022-12-12T05:40:07.591+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2022-12-12T05:40:07.656+0000] {logging_mixin.py:137} INFO - [2022-12-12T05:40:07.644+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 6, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2022-12-12T05:40:07.660+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2022-12-12T05:40:07.775+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etl.py took 0.276 seconds
[2022-12-12T05:40:37.871+0000] {processor.py:153} INFO - Started process (PID=353) to work on /opt/airflow/dags/etl.py
[2022-12-12T05:40:37.875+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2022-12-12T05:40:37.880+0000] {logging_mixin.py:137} INFO - [2022-12-12T05:40:37.880+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2022-12-12T05:40:37.899+0000] {logging_mixin.py:137} INFO - [2022-12-12T05:40:37.894+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 6, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2022-12-12T05:40:37.902+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2022-12-12T05:40:37.949+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etl.py took 0.085 seconds
[2022-12-12T05:41:09.069+0000] {processor.py:153} INFO - Started process (PID=414) to work on /opt/airflow/dags/etl.py
[2022-12-12T05:41:09.083+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2022-12-12T05:41:09.112+0000] {logging_mixin.py:137} INFO - [2022-12-12T05:41:09.112+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2022-12-12T05:41:09.298+0000] {logging_mixin.py:137} INFO - [2022-12-12T05:41:09.274+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 6, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2022-12-12T05:41:09.317+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2022-12-12T05:41:09.525+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etl.py took 0.465 seconds
[2022-12-12T05:41:40.062+0000] {processor.py:153} INFO - Started process (PID=477) to work on /opt/airflow/dags/etl.py
[2022-12-12T05:41:40.075+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2022-12-12T05:41:40.081+0000] {logging_mixin.py:137} INFO - [2022-12-12T05:41:40.081+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2022-12-12T05:41:40.108+0000] {logging_mixin.py:137} INFO - [2022-12-12T05:41:40.097+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 6, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2022-12-12T05:41:40.117+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2022-12-12T05:41:40.246+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etl.py took 0.196 seconds
[2022-12-12T05:42:12.091+0000] {processor.py:153} INFO - Started process (PID=537) to work on /opt/airflow/dags/etl.py
[2022-12-12T05:42:12.170+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/etl.py for tasks to queue
[2022-12-12T05:42:12.233+0000] {logging_mixin.py:137} INFO - [2022-12-12T05:42:12.232+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/etl.py
[2022-12-12T05:42:12.645+0000] {logging_mixin.py:137} INFO - [2022-12-12T05:42:12.531+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl.py", line 6, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2022-12-12T05:42:12.708+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/etl.py
[2022-12-12T05:42:13.480+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/etl.py took 1.795 seconds
